[package]
name = "raptor"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
readme = "README.md"
description = "Build disk images, file archives and bootable isos with a simple, docker-inspired syntax"
categories = ["config", "command-line-utilities", "virtualization", "template-engine"]
repository = "https://github.com/chrivers/raptor"
keywords = ["devops", "reproducible", "disk-image", "generation"]

[dependencies]
camino = "1.1.9"
clap = { version = "4.5.20", features = ["derive"] }
colog = "1.3.0"
hand = "0.1.2"
indicatif = { version = "0.17.8", features = ["improved_unicode"] }
log = "0.4.22"
minijinja = { version = "2.4.0", features = ["custom_syntax", "debug", "loader"] }
pest = { version = "2.7.14", features = ["miette-error", "pretty-print"] }
pest_ascii_tree = "0.1.0"
pest_consume = "1.1.3"
pest_derive = "2.7.14"
pretty_env_logger = "0.5.0"
thiserror = "1.0.67"
