use itertools::Itertools;
use minijinja::Environment;

#[allow(clippy::needless_pass_by_value)]
pub fn header(comment_start: Option<&str>, comment_end: Option<&str>) -> String {
    let a = comment_start.unwrap_or("## ");
    let b = comment_end.unwrap_or("");

    [
        "--------------------------------------",
        "Generated by Raptor ",
        "",
        "THIS FILE IS AUTOMATICALLY GENERATED.",
        "DO NOT EDIT. ALL CHANGES WILL BE LOST.",
        "--------------------------------------",
    ]
    .iter()
    .map(|line| format!("{a}{line}{b}"))
    .join("\n")
}

pub fn add_functions(env: &mut Environment) {
    env.add_function("header", header);
}
