[book]
authors = ["Christian Iversen"]
language = "en"
src = "src"
title = "Raptor Manual"

[build]
create-missing = false

[preprocessor.alerts]

[preprocessor.pikchr]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
smart-punctuation = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]

# to build custom highlight.js:
#
# node ./tools/build.js -t browser plaintext dockerfile raptorfile rust diff json yaml nginx
#
# cp highlight.js/build/highlight.js theme/highlight.js
