name: mdbook-deploy

on:
  push:
    branches:
      - main
      - chrivers/mdbook

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install mdBook
        run: |
          export MDBOOK_URL=https://github.com/rust-lang/mdBook/releases/download/v0.4.52/mdbook-v0.4.52-x86_64-unknown-linux-gnu.tar.gz
          export MDBOOK_ADMONISH_URL=https://github.com/tommilligan/mdbook-admonish/releases/download/v1.20.0/mdbook-admonish-v1.20.0-x86_64-unknown-linux-musl.tar.gz
          curl -L ${MDBOOK_URL}          | sudo tar -C /usr/local/bin -xz
          curl -L ${MDBOOK_ADMONISH_URL} | sudo tar -C /usr/local/bin -xz

      - name: Install mdbook-pikchr from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: mdbook-pikchr

      - name: Build the book
        run: mdbook build book

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book
